version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
  main:
    build: .
    ports:
      - 3000:3000
    environment:
      SITE_URL: http://localhost:3000/
      DB_USER: test
      DB_PASSWORD: test
      DB_PORT: 5432
      DB_HOST: db
      DB_DATABASE: test
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      JWT_SECRET: test_key